parameters:
    pq.request_limit.class: PQstudio\RateLimitBundle\Utility\RequestLimit
    pq.rate_limit.listener.class: PQstudio\RateLimitBundle\EventListener\RateLimitListener
    pq.rate_limit.storage.redis.class: PQstudio\RateLimitBundle\Storage\RedisStorage
    pq.rate_limit.exception.listener.class: PQstudio\RateLimitBundle\EventListener\ExceptionListener

services:
    pq.request_limit:
        class: %pq.request_limit.class%

    pq.rate_limit.listener:
        class: %pq.rate_limit.listener.class%
        arguments:
            requestLimit: @pq.request_limit
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
              
    pq.rate_limit.storage.redis:
        class: %pq.rate_limit.storage.redis.class%
        arguments:
            redis: @snc_redis.default
            security: @security.context
            requestLimit: @pq.request_limit

    pq.rate_limit.exception.listener:
        class: pq.rate_limit.exception.listener.class
        arguments:
            jmsSerializer: @jms_serializer
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
